const styles = {
  main: { maxWidth: 520, margin: "0 auto", padding: "96px 24px 64px" },
  back: { color: "#D49A56", textDecoration: "none", fontSize: 14 },
  panel: {
    marginTop: 28,
    padding: "32px",
    backgroundColor: "rgba(48, 39, 32, 0.72)",
    border: "1px solid #493A2D",
    borderTop: "4px solid #B7623D",
    borderRadius: 12,
  },
  kicker: {
    color: "#D49A56",
    fontFamily: "'Courier New', monospace",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 2,
  },
  title: {
    color: "#F1DFC2",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: "clamp(36px, 6vw, 52px)",
    margin: "12px 0",
  },
  intro: { color: "#BFB2A1", lineHeight: 1.6 },
  label: { display: "block", color: "#F1DFC2", margin: "20px 0 8px" },
  input: {
    boxSizing: "border-box",
    width: "100%",
    padding: 12,
    color: "#F1DFC2",
    backgroundColor: "#211C18",
    border: "1px solid #5C4938",
    borderRadius: 8,
    fontSize: 16,
  },
  button: {
    width: "100%",
    marginTop: 28,
    padding: 14,
    color: "#171411",
    backgroundColor: "#E7B86A",
    border: 0,
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  error: { color: "#F2A69A", lineHeight: 1.5 },
  success: { color: "#C7D5B1", lineHeight: 1.5 },
  switch: { color: "#BFB2A1", marginTop: 24 },
  link: { color: "#D49A56" },
};

export default styles;
